"""add Department

Revision ID: 48017765f956
Revises: 747c6a547896
Create Date: 2025-01-16 13:31:06.922479

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '48017765f956'
down_revision = '747c6a547896'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('department',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('address', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('department')
    # ### end Alembic commands ###
